name: Move Business Central Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  MoveAllArtifacts:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Move
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
          FEED_TOKEN: ${{ secrets.FEED_TOKEN }}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "MoveAll.ps1")

