name: Copy All Artifacts to Universal Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  MoveAllArtifacts:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Move
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
          FEED_TOKEN: ${{ secrets.FEED_TOKEN }}
          UNIVERSAL_FEED: ${{ secrets.UNIVERSAL_FEED }}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "UpdatePublicUniversalFeeds.ps1")

